### ISSUE TITLE
MacOS docker image ca certificate error

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-collector#4579]
**Describe the bug**
I am using [the official docker image for the collector](https://hub.docker.com/r/otel/opentelemetry-collector), and defined an exporter of type otlphttp with https endpoint. When run, I get the following error from the collector: 

```
2021-12-19T15:39:14.758Z        info    exporterhelper/queued_retry.go:325      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "name": "otlphttp", "error": "failed to make an HTTP request: Post \"https://otelcol.aspecto.io/v1/traces\": x509: certificate signed by unknown authority", "interval": "35.604692186s"}
```

**Steps to reproduce**
docker command:
```
docker run -p9411:9411 -v "$(pwd)":/etc -it --rm otel/opentelemetry-collector --config /etc/zipkin-to-otlp.yaml
```

config:
```yaml
receivers:
  zipkin:

exporters:
  logging:
    loglevel: debug
  otlphttp:
    endpoint: https://otelcol.aspecto.io

service:
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [logging, otlphttp]
```

send a trace to the zipkin endpoint.

**What did you expect to see?**
expected the export to https otlp endpoint to work

**What did you see instead?**
the error: "x509: certificate signed by unknown authority"

**What version did you use?**
tried with the following versions:
- 0.33.0
- 0.35.0 (tagged "latest" in dockerhub)
- 0.41.0 - newest version

**What config did you use?**
config attached above

**Environment**
MacOS

**Additional context**
- When I compile the collector myself and use the same config (not from the official docker image), there is no error.
- Tried also exporting to "https://google.com" (just to check the certificate) and it also complains about "unknown authority" on the google domain.
Tried to set
```
tls:
  insecure: true
```
as described in the README and it still complains about the certificate (I guess it's a different issue).

- The endpoint certificate for `https://otelcol.aspecto.io` is valid and works in many other scenarios. It is consistently not working when using the official docker image. verified with multiple machines.

- I checked the [Dockerfile](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4b2adb67f416b5e8a4068ee54729fd4c9ade9cd9/cmd/otelcontribcol/Dockerfile#L2) and saw that the ca certificates are copied into the docker image upon build. Mabye they are expired or something? When I tried to `docker exec -it ID /bin/sh` into the container I get "OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown". also did not work with `/bin/bash` and `/bin/ash`. How do I start a shell in the container?

Any help will be appriciated

**Comment by jpkrohling** [comment]
Are you able to have a similar test with the core image?

**Comment by jpkrohling** [comment]
To make this test easier, I just pushed an image of contrib built from the -releases to this location: jpkroehling/opentelemetry-collector-contrib:0.41.0-SNAPSHOT-5ddd7d9-amd64 . Would you be able to try it out?

**Comment by blumamir** [comment]
> To make this test easier, I just pushed an image of contrib built from the -releases to this location: jpkroehling/opentelemetry-collector-contrib:0.41.0-SNAPSHOT-5ddd7d9-amd64 . Would you be able to try it out?

Thanks for the help with this issue, tested with this image and I still get the same error: "x509: certificate signed by unknown authority". 
Tried the same setup on linux and it seems to work, so the issue is observed only for MacOS and docker. I am running on macOS Catalina 10.15.7, with Docker Desktop version 3.5.2

**Comment by jpkrohling** [comment]
I would need some help from someone on a similar setup though. If you can sort it out and send in a PR, I'll gladly review it.

**Comment by blumamir** [comment]
> > docker run ... -v "$(pwd)":/etc ...
> 
> You're overwriting the entire `/etc/` directory tree, which includes the ca-certificates trust stores.

What a silly mistake 🤦‍♂️ . Thank you so much!! I was so lost with this issue

**Comment by jpkrohling** [comment]
Great catch, @seankhliao!
