### ISSUE TITLE
Excessively high memory usage when using client-side zstd compression in confighttp

### ISSUE THREAD

**Issue by swiatekm** [open-telemetry/opentelemetry-collector#8216]
**Describe the bug**
We've added zstd support to the server side of confighttp in #7927. I rolled this out for OTLP traffic between an agent and a gateway in a K8s environment and saw very significant increase in memory consumption on the client side.

**Steps to reproduce**
I have some memory profiles saved of this, and I'm planning to create a self-contained reproduction, ideally with just synthetic benchmarks.

**What did you expect to see?**
Memory consumption in the ballpark of what other compression methods use.

**What did you see instead?**
Memory consumption for otlphttp exporter using zstd more than 10x the amount for gzip.

**What version did you use?**
Version: 0.82.0

**What config did you use?**
The relevant part:
```yaml
exporters:
  otlphttp:
    endpoint: ...
    compression: zstd
processors:
   batch:
    send_batch_max_size: 2000
    send_batch_size: 1000
    timeout: 1s
```

**Environment**
Kubernetes 1.24, EKS to be precise.

**Additional context**
 I'm reporting this as is so it doesn't get lost and to consolidate reports in case other users experience this. Will update with more data once I'm able to.

**Comment by swiatekm-sumo** [comment]
I managed to reproduce this in a test K8s cluster. I've also written some benchmarks which demonstrate the problem, although this is somewhat challenging for reasons which I'll elaborate upon.

The test cluster had a synthetic workload generating 10k log lines per second running. The resource consumption as reported by `kubectl top` was, respectively:

### With gzip compression

```text
otelcol-logs-collector-5mdw2     593m         79Mi            
```
### With zstd compression

```text
otelcol-logs-collector-4jc6b     526m         469Mi           
```
![zstd-profile-k8s-logs](https://github.com/open-telemetry/opentelemetry-collector/assets/93588780/649c34b8-744c-4fa2-a019-6ffd11bb71de)

**Comment by atoulme** [comment]
Would you like to submit a PR to fix the issue?

**Comment by swiatekm-sumo** [comment]
@atoulme I'll try when I get the time. I still don't understand why the problem is as severe as it is. My fix is effective, so I must be roughly correct about the root cause, but I'd like to try to understand it better before submitting.

**Comment by rnishtala-sumo** [comment]
@swiatekm-sumo @atoulme here are some of my findings on this. I deployed the otel collector on a k8s cluster today with atleast 50 nginx pods generating a new log every second. The difference seen in the memory usage with both the compression types is below:

- gzip: `sumo-sumologic-otelcol-logs-collector-vqp5z      124m         74Mi`
- zstd: `sumo-sumologic-otelcol-logs-collector-4r92s      138m         106Mi`

The difference in memory usage wasn't 10x as seen previously. I used `0.94.0` for testing. I let the collector run for atleast an hour.

**Comment by rnishtala-sumo** [comment]
@swiatekm-sumo @atoulme 

v0.92.0
zstd: `sumo-sumologic-otelcol-logs-collector-2lk4k      245m         250Mi`
gzip: `sumo-sumologic-otelcol-logs-collector-x2wmp      291m         84Mi`

v0.94.0
gzip: `sumo-sumologic-otelcol-logs-collector-djwmz      199m         73Mi`
zstd: `sumo-sumologic-otelcol-logs-collector-v8pjr      198m         118Mi`

There seems to be some improvement in `0.94.0` which used a later version (v0.17.5) of the `compress` library that has some `zstd` changes.
https://github.com/klauspost/compress/releases/tag/v1.17.5


Apart from the above, there was a known memory leak with using `zstd` with a `sync.Pool` that was addressed in `v0.15.0` by adding the option to disable concurrency which does not allow spawning new goroutines as explained here
- https://github.com/klauspost/compress/issues/264

A possible change we could make here is to simply use `zstd.WithDecoderConcurrency(1)` as mentioned in this PR, which prevents goroutine leaks
https://github.com/segmentio/kafka-go/pull/889

**Comment by atoulme** [comment]
Thank you for this inquiry and providing data, I appreciate it. Do we have appropriate benchmarks for zstd usage that we could use to test the simple change you mention?

**Comment by rnishtala-sumo** [comment]
I can work on the benchmarks to test the zstd compression with and without concurrency enabled. I do want to emphasize that the `zstd` memory usage in `v1.17.5` of the `compress` package seems to be lesser than in `v0.17.4` from running tests on a k8s cluster.

**Comment by rnishtala-sumo** [comment]
Created the following draft PR for this, to show the difference in memory allocation with concurrency disabled - https://github.com/open-telemetry/opentelemetry-collector/pull/9749

**Comment by swiatekm-sumo** [comment]
Resolved in #9749

**Comment by djluck** [comment]
Just to add: this issue appears to be still an issue in the latest version even with the above MR for _server side HTTP receivers_:
![image](https://github.com/user-attachments/assets/fb38ed22-3d93-4505-a1fa-7b6900ae03c4)

I'm seeing constant crash loops having zstd enabled with almost all memory associated with zstd codepaths.

**Comment by swiatekm** [comment]
@djluck that's strange given that the server side appears to already have our client-side fix implemented. Can you open a new issue with your findings?

**Comment by djluck** [comment]
Sure thing @swiatekm

**Comment by inge4pres** [comment]
> I'm seeing constant crash loops having zstd enabled with almost all memory associated with zstd codepaths.

We recently stumbled on a panic in `otlphttpconfig` when trying to process data with `zstd`.
@carsonip traced it back to a bug in the usage of `sync.Pool`.
He is working on creating an issue for it and has done an excellent investigation that will lead to a PR fixing the bug.

@djluck is this the same stacktrace you're seeing in your crashes?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa68c0]

goroutine 2185 [running]:
io.ReadAtLeast({0x0, 0x0}, {0x4006e6bab8, 0x3, 0x8}, 0x3)
	io/io.go:335 +0x70
io.ReadFull(...)
	io/io.go:354
github.com/klauspost/compress/zstd.(*readerWrapper).readSmall(0x4002e5a878?, 0x3)
	github.com/klauspost/compress@v1.18.0/zstd/bytebuf.go:86 +0x4c
github.com/klauspost/compress/zstd.(*frameDec).reset(0x40066318c8, {0x4fbc1f8, 0x4006e6baa8})
	github.com/klauspost/compress@v1.18.0/zstd/framedec.go:82 +0xf0
github.com/klauspost/compress/zstd.(*Decoder).nextBlockSync(0x4006e6ba00)
	github.com/klauspost/compress@v1.18.0/zstd/decoder.go:485 +0xb4
github.com/klauspost/compress/zstd.(*Decoder).nextBlock(0x4006e6ba00, 0xc0?)
	github.com/klauspost/compress@v1.18.0/zstd/decoder.go:421 +0x3c
github.com/klauspost/compress/zstd.(*Decoder).Read(0x4006e6ba00, {0x400891e000?, 0x4002e5aa58?, 0xa1300?})
	github.com/klauspost/compress@v1.18.0/zstd/decoder.go:145 +0x11c
go.opentelemetry.io/collector/config/confighttp.(*pooledZstdReadCloser).Read(0x3f83bc0?, {0x400891e000?, 0x1?, 0x400252a000?})
	go.opentelemetry.io/collector/config/confighttp@v0.135.0/compression.go:56 +0x24
net/http.(*maxBytesReader).Read(0x4005e88ec0, {0x400891e000?, 0x40002f4330?, 0x1?})
	net/http/request.go:1225 +0x60
io.copyBuffer({0xfd24e8a4c648, 0x4004d301a0}, {0xfd24e8a4c480, 0x4005e88ec0}, {0x400891e000, 0x8000, 0x8000})
	io/io.go:429 +0x18c
io.CopyBuffer({0xfd24e8a4c648?, 0x4004d301a0?}, {0xfd24e8a4c480?, 0x4005e88ec0?}, {0x400891e000?, 0x2ae0c?, 0x10?})
	io/io.go:402 +0x38
net/http.(*transferWriter).doBodyCopy(0x4008914460, {0xfd24e8a4c648, 0x4004d301a0}, {0xfd24e8a4c480, 0x4005e88ec0})
	net/http/transfer.go:417 +0xac
net/http.(*transferWriter).writeBody(0x4008914460, {0x4f77ae0, 0x40094fef00})
	net/http/transfer.go:361 +0x59c
net/http.(*Request).write(0x400198b900, {0x4f77ae0, 0x40094fef00}, 0x0, 0x0, 0x0)
	net/http/request.go:762 +0x818
net/http.(*persistConn).writeLoop(0x40057e3200)
	net/http/transport.go:2600 +0xf4
created by net/http.(*Transport).dialConn in goroutine 2178
	net/http/transport.go:1945 +0x1164
```

**Comment by inge4pres** [comment]
> [@carsonip](https://github.com/carsonip) traced it back to a bug in the usage of `sync.Pool`. He is working on creating an issue for it and has done an excellent investigation that will lead to a PR fixing the bug.

Issue: https://github.com/open-telemetry/opentelemetry-collector/issues/13954
PR: https://github.com/open-telemetry/opentelemetry-collector/pull/13955

**Comment by swiatekm** [comment]
I'm closing this again until we get another credible report of this issue still being present.
